### ISSUE TITLE
All TS cmdlets return the same error

### ISSUE THREAD

**Issue by alex-frankel** [Azure/template-specs#1]
```powershell
New-AzTemplateSpec -Name firstSpec -Version 1.0 -ResourceGroupName brittle-hollow -Location eastus -TemplateJsonFile C:\Users\alfran\repos\personal-arm-templates\ARM-Templates\testing\basicLinkedTemplateSpec\mainTemplate.json
```

returns:
New-AzTemplateSpec: Operation returned an invalid status code 'NotFound'

```powershell
Get-AzTemplateSpec
```
returns:
Get-AzTemplateSpec: Operation returned an invalid status code 'NotFound'

**Comment by captainhook** [comment]
@alex-frankel what do you mean by whitelisting? I am getting the same error and can't figure out what to do.
