### ISSUE TITLE
Status Message: Unable to retrieve the template content from the resource ID

### ISSUE THREAD

**Issue by slavizh** [Azure/template-specs#24]
I am getting error when I try to deploy a template spec that I have uploaded. Error is:

```
New-AzDeployment: 14:14:31 - The deployment 'stan66' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Unable to retrieve the template content from the resource ID '/subscriptions/<sub id>/resourceGroups/templateSpecRG/providers/Microsoft.Resources/templateSpecs/lz-automation-account-monitoring/versions/2.0.0'. Please see https://aka.ms/arm-deploy for usage details. Diagnostic information: timestamp '20200722T111428Z', tracking Id 'e5021d18-c55a-4def-b027-279ec3c20d30', request correlation Id '749f31ff-9725-4ffd-a9e5-1590386a18a2'. (Code:InvalidTemplateSpec)
CorrelationId: 749f31ff-9725-4ffd-a9e5-1590386a18a2
```

If needed I can provide more information in private.

**Comment by outifaout** [comment]
I have the same issue, even when I change the region from West Europe to West US 2.. 
Has this been identified as a bug? has it been fixed?

**Comment by alex-frankel** [comment]
Can you confirm that you have access to the template spec resource? Can you share the error you are getting and a correlation ID if you have one?

**Comment by outifaout** [comment]
Yes I do have access. This is the error I get : 
##[error]InvalidTemplateSpec: Unable to retrieve the template content from the resource ID '/subscriptions/ad4b8e8f-6b90-42ef-85f4-f96352fc1dd6/resourceGroups/tr-rg-dev-templateSpecs/providers/Microsoft.Resources/templateSpecs/tr-ts-dev-cdnAndStorage/versions/1.0'. Please see https://aka.ms/arm-deploy for usage details. Diagnostic information: timestamp '20210208T132331Z', tracking Id '0ad51886-2031-4100-83ad-93121dac6b28', request correlation Id 'cce11fe4-5c6f-4ee9-89a2-3d6dea2d0569'.

**Comment by snarkywolverine** [comment]
This is a permissions issue - it looks like the identity that created the template spec is is different than the identity deploying the template spec.  Try deploying with the former identity, or verifying that the latter has permissions to TemplateSpecs.
