### ISSUE TITLE
How will template specs integrate with Azure DevOps? 

### ISSUE THREAD

**Issue by lunar87** [Azure/template-specs#30]
Although you can version template specs, how do you see integrate template authoring lifecycle with source contral as well as template spec deployements with Azure DevOps pipelines? Are there template spec pipeline tasks that are planned to assist with this?

**Comment by jatinbhalla** [comment]
I have main and linked templates in Azure repo and using Azure powershell in CI i was trying to create template spec. but CI throws an error.
##[error]The term 'Get-AzTemplateSpec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

While these commands are working fine from local machine. Can someone help me to resolve this

**Comment by alex-frankel** [comment]
My guess is the Azure PowerShell DevOps task is not up to date with the latest version of the public PowerShell Az module. You should be able to [install the latest version](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.3.0#install-for-current-user) as part of your pipeline task before calling the `*-AzTemplateSpec` tasks that you need.
