### ISSUE TITLE
Deploy specific version of the template using portal or other mediums

### ISSUE THREAD

**Issue by itshemant09** [Azure/template-specs#35]
May be I am missing something but Suppose If  I have a multiple versions of my template and I want to deploy specific version. How I can deploy it?

![image](https://user-images.githubusercontent.com/16230131/90346498-fa4e7600-e046-11ea-8c12-ac55ecf0a058.png)

I do not find any option to deploy specific version. How to to it via PowerShell or CLI?

**Comment by stuartko** [comment]
As of late August you can now deploy a specific version via the portal by right clicking on any version within a template spec, or by choosing deploy from the version page itself.

![image](https://user-images.githubusercontent.com/47676853/97650083-25c1e980-1a16-11eb-9058-cb51ad94087a.png)
