### ISSUE TITLE
New-AzDeployment : Cannot retrieve the dynamic parameters for the cmdlet when deploying to different subscription then the subscription storing the templateSpec

### ISSUE THREAD

**Issue by stweb1963** [Azure/template-specs#40]
If you deploy to a different subscription then the one the templateSpec is stored you receive the following error

New-AzDeployment : Cannot retrieve the dynamic parameters for the cmdlet. Operation returned an invalid status code 'NotFound'
At line:1 char:1
+ New-AzDeployment -TemplateSpecId /subscriptions/c304833c-8a28-41f4-96 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzDeployment], ParameterBindingException
    + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureSubscriptionDeploymentCmdlet

We would store/manage all our templateSpecs / versions within a single HUB subscription

All deployments would consume this each managed templateSpec/version for any deployment across all subscriptions

**Comment by stuartko** [comment]
The fix for this has now been released with v5.2.0

https://github.com/Azure/azure-powershell/releases/tag/v5.2.0-December2020
