### ISSUE TITLE
Deploying Template-spec at Subscription level from portal fails

### ISSUE THREAD

**Issue by TEJ975** [Azure/template-specs#42]
Validation fails with error stating 'location' property must be specified for the deployment. Deployment parameters mentions   'Region' parameter?

**Comment by alex-frankel** [comment]
Thanks for reporting. I was able to repro on my end as well. A lot of people are out since we are close to christmas/new year's, but we will take a look when we are back on the Jan 4th

**Comment by alex-frankel** [comment]
This should be fixed.
