### ISSUE TITLE
New-AzResourceGroupDeployment Fails to determine dynamic (template) parameters when using the TemplateUri

### ISSUE THREAD

**Issue by brwilkinson** [Azure/template-specs#45]
Sample Template for demo purposed

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "foo": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "bar": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        }
    },
    "functions": [],
    "variables": {
        
    },
    "resources": [],
    "outputs": {
        "foo": {
            "type": "string",
            "value": "[parameters('foo')]"
        },
        "bar": {
            "type": "string",
            "value": "[parameters('bar')]"
        }
    }
}
```

Sample param file for Demo 

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "bar": {
            "value": "AZE2"
        },
        "foo": {
            "value": "helo"
        }
    }
}
```

**Comment by brwilkinson** [comment]
### Works as expected

![image](https://user-images.githubusercontent.com/3605266/105538284-069ac700-5ca8-11eb-80f5-ef06b96270af.png)

```powershell
New-AzResourceGroupDeployment @Params 

DeploymentName          : nestedTest
ResourceGroupName       : AZC1-BRW-ABC-RG-S1
ProvisioningState       : Succeeded
Timestamp               : 1/21/2021 11:44:56 PM
Mode                    : Incremental
TemplateLink            : 
                          Uri            : https://azc1brwhubg1saglobal.blob.core.windows.net/azc1-abc-stageartifacts-benwilk/templates-nested/nestedTest.json
                          ContentVersion : 1.0.0.0

Parameters              : 
                          Name             Type                       Value     
                          ===============  =========================  ==========
                          foo              String                     helo      
                          bar              String                     AZE2

Outputs                 :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     helo
                          bar              String                     AZE2

DeploymentDebugLogLevel :
```

**Comment by brwilkinson** [comment]
### Works as expected

![image](https://user-images.githubusercontent.com/3605266/105538429-3b0e8300-5ca8-11eb-9dbf-eb67405d6c9c.png)

```powershell
New-AzResourceGroupDeployment @Params 

ProvisioningState       : Succeeded
Timestamp               : 1/21/2021 11:45:19 PM
Mode                    : Incremental
TemplateLink            :
                          Uri            : https://azc1brwhubg1saglobal.blob.core.windows.net/azc1-abc-stageartifacts-benwilk/templates-nested/nestedTest.json
                          ContentVersion : 1.0.0.0

Parameters              : 
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     abc
                          bar              String                     123

Outputs                 :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     abc
                          bar              String                     123

DeploymentDebugLogLevel :
```

**Comment by brwilkinson** [comment]
Works as expected### 

![image](https://user-images.githubusercontent.com/3605266/105538566-7315c600-5ca8-11eb-9d3a-3e47d3367cbe.png)
New-AzResourceGroupDeployment @Params 

DeploymentName          : nestedTest
ResourceGroupName       : AZC1-BRW-ABC-RG-S1
ProvisioningState       : Succeeded
Timestamp               : 1/21/2021 11:46:06 PM
Mode                    : Incremental
TemplateLink            :
Parameters              :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     helo
                          bar              String                     AZE2

Outputs                 :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     helo
                          bar              String                     AZE2

DeploymentDebugLogLevel :
```powershell



````

**Comment by brwilkinson** [comment]
### Works as expected

![image](https://user-images.githubusercontent.com/3605266/105538706-a9ebdc00-5ca8-11eb-8044-21f6cc6d97ce.png)

```powershell
New-AzResourceGroupDeployment @Params 

DeploymentName          : nestedTest
ResourceGroupName       : AZC1-BRW-ABC-RG-S1
ProvisioningState       : Succeeded
Timestamp               : 1/21/2021 11:47:10 PM
Mode                    : Incremental
TemplateLink            :
Parameters              :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     abc
                          bar              String                     AZE2

Outputs                 :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     abc
                          bar              String                     AZE2
```

**Comment by brwilkinson** [comment]
This now breaks . . . using TemplateURI

![image](https://user-images.githubusercontent.com/3605266/105539401-8aa17e80-5ca9-11eb-9d81-06a51e62603a.png)

```powershell
New-AzResourceGroupDeployment @Params

New-AzResourceGroupDeployment:
Line |
  10 |  New-AzResourceGroupDeployment @Params
     |                                ~~~~~~~
     | A parameter cannot be found that matches parameter name 'foo'.
```

Also when update when you remove foo . . .

![image](https://user-images.githubusercontent.com/3605266/105539500-ae64c480-5ca9-11eb-97d1-21fefdfc3864.png)

```powershell
New-AzResourceGroupDeployment @Params 

New-AzResourceGroupDeployment: 
Line |
  10 |  New-AzResourceGroupDeployment @Params
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 3:50:59 PM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The value for the template parameter 'foo' at line '5' and column '16' is not provided. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.

New-AzResourceGroupDeployment:
Line |
  10 |  New-AzResourceGroupDeployment @Params
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The deployment validation failed
```

**Comment by brwilkinson** [comment]
I demoed with splatting for simplicity, however, same goes for using the parameters inline.

```powershell
New-AzResourceGroupDeployment -queryString $queryString -TemplateUri $TemplateURi -ResourceGroupName $rgName -TemplateParameterFile $myParams -foo abc
```

**Comment by brwilkinson** [comment]
@alex-frankel just wanted to tag you on this one, since I didn't see anyone pick up this issue.

This is a blocker for me deploying via template specs, I wanted to keep moving forward on my testing/implementation.

**Comment by alex-frankel** [comment]
@Xynoclafe is working on a fix. We will update this with the azure-powershell PR once it's out.

**Comment by Xynoclafe** [comment]
@brwilkinson @alex-frankel The PR was merged. The fix should be included with the next release.
https://github.com/Azure/azure-powershell/pull/14132

**Comment by brwilkinson** [comment]
Thank you @alex-frankel @Xynoclafe ✅

**Comment by brwilkinson** [comment]
Hi @Xynoclafe 

just checking on the new modules

![image](https://user-images.githubusercontent.com/3605266/109747955-e30f4a00-7b8c-11eb-9921-0f6582dc8397.png)

Did the fix not make it into 3.3.0  [Az.Resources]?

I still see the same issue..

![image](https://user-images.githubusercontent.com/3605266/109748078-14881580-7b8d-11eb-91a2-ff5b9b641866.png)

![image](https://user-images.githubusercontent.com/3605266/109748026-00dcaf00-7b8d-11eb-8bdb-c67a77779103.png)

**Comment by Xynoclafe** [comment]
Hi @brwilkinson 
The fix should be present in Az Modules 5.6.0.
In the screenshots you added, my guess is that the error is due to the "?" at the start of the QueryString. -QueryString takes the SASToken without the preceding "?".

**Comment by brwilkinson** [comment]
@Xynoclafe  aah good catch, thank you.

It's interesting however I tested both cases here before replying and one of them works with the ?

### works reading both from param file

![image](https://user-images.githubusercontent.com/3605266/109840388-ecd09600-7bfc-11eb-90a1-8d66e50a73dc.png)

### doesn't work with the dynamic param

![image](https://user-images.githubusercontent.com/3605266/109840564-18ec1700-7bfd-11eb-9164-f0f24b6c7086.png)

### as you pointed out, the correct syntax does work. . . .

####  thinking about this it would be nice if the querystring was normalized to work with or without the ? often a copy/paste will always include it from storage explorer etc.

![image](https://user-images.githubusercontent.com/3605266/109840860-5c468580-7bfd-11eb-9dba-885abcfd8cc4.png)

**Comment by brwilkinson** [comment]
oops deleted my comment, take 2.

Thanks @Xynoclafe good catch.

Yes it does work as expected without the ?

![image](https://user-images.githubusercontent.com/3605266/109841783-41284580-7bfe-11eb-9930-6221f3e03a58.png)

I did test this before posting yesterday and it works with the ? when not using dynamic params.

Not sure why this doesn't fail ? with the  ?

![image](https://user-images.githubusercontent.com/3605266/109842575-0e328180-7bff-11eb-8ec5-e2fae15114d5.png)

It would be nice if the string was normalized to remove the ?, since when you copy it from storage explorer etc, it is always included.

obviously the same with dynamic, which is what I showed yesterday fails.... 

![image](https://user-images.githubusercontent.com/3605266/109843210-af213c80-7bff-11eb-8338-b7f2a176bee9.png)

Anyway, thank you, I look forward to testing this more on Template Specs.

**Comment by alex-frankel** [comment]
Closing since the initial issue is resolved. @brwilkinson we are planning to normalize this behavior I believe. @snarkywolverine - did we end up implementing that already?

**Comment by snarkywolverine** [comment]
Yes, you can now either include or omit the leading ? for the queryString.

**Comment by brwilkinson** [comment]
Thanks @snarkywolverine 

we may have found a scenario that is not stripping the ?

When using a dynamic param... it doesn't normalize.

There was a recent update to make this work, so perhaps a regression on that functionality?

This was the update Azure/azure-powershell#14132 

![image](https://user-images.githubusercontent.com/3605266/109879315-49967580-7c2a-11eb-9138-21059d2d569c.png)

**Comment by Xynoclafe** [comment]
@brwilkinson The behavior right now is as expected since dynamic parameters are resolved before the "?" is normalized. We can definitely add the "?" normalization to the dynamic parameters scenario as well in a future version.

**Comment by SvenAelterman** [comment]
@Xynoclafe I have Az.Resources 3.4.1 in an Azure Automation account. When using the `New-AzResourceGroupDeployment` cmdlet in a PowerShell runbook, I get an error that the parameter isn't specified when it's not in the parameters file. When I specify the parameter in the parameters file and then specify it as a dynamic parameter, the dynamic parameter value doesn't override the value from the template file (but no error is thrown).

Here's what my command looks like:
```
New-AzResourceGroupDeployment -ResourceGroupName "rg-filesynctoblob-demo-eastus-01" `
    -Name "filesynctoblob-aci" `
    -fileShareSasUri $ShareSASURI -blobSasUri $ContainerSASURI `
    -commandParameter $command `
    -QueryString $aciTemplateSASURI `
    -TemplateUri $templateUri -TemplateParameterUri $parameterUri
```

The $templateUri does not contain the SAS token querystring; therefore I specify the QueryString param. However, the QueryString param does not seem to affect the -TempalteParamaterUri param, so my SAS token is in $parameterUri.
