### ISSUE TITLE
missing 'StrongType' experience in GUI

### ISSUE THREAD

**Issue by azMantas** [Azure/template-specs#47]
it would be great to use 'strongType'  functionality for our portal users.  
That's what I have in my tempalte parameters file
```
  "parameters": {
        "resourceTypes": {
            "type": "String",
            "metadata": {
                "strongType": "Microsoft.Network/virtualNetworks/subnets"
            }
        },
        "location": {
            "type": "string",
            "metadata": {
                "strongType": "location"
            }
        },
        "vmSKUs": {
            "type": "string",
            "metadata": {
                "strongType": "vmSKUs"
            }
        },
        "existingResourceGroups": {
            "type": "string",
            "metadata": {
                "strongType": "existingResourceGroups"
            }
        },
        "thatWorks": {
            "type": "String",
            "defaultValue": "123",
            "allowedValues": [
                "abc",
                "def",
                "123"
            ],
            "metadata": {
                "strongType": "thatWorks"
            }
        }
    },
```
    and that's how it looks like in a portal. 
![image](https://user-images.githubusercontent.com/47916866/107980868-4ad86900-6fc1-11eb-8a86-2862fad8d7ce.png)

**Comment by alex-frankel** [comment]
We are going to be supporting [createUiDefinition](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/create-uidefinition-overview) to support this scenario going forward. This should give you a lot more capability than what is currently possible with policy's `strongType`.

**Comment by azMantas** [comment]
great! can we expect to get this functionality before summer?

**Comment by alex-frankel** [comment]
Yes it should be done by then - cc @apclouds and @TarunSunkaraneni as FYI

**Comment by kmgrime** [comment]
@alex-frankel Last update here was 1 year ago - anything new?

**Comment by alex-frankel** [comment]
The equivalent of strong type is provided by the UiFormDefinition JSON file which you can associate with a Template Spec. We detailed this in #58, so I'm going to close this one.
